version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:

  database:
    image: typezero-labs/incontrol-api-db:latest
    build: ./postgres/
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file:
      - ./environments/local.env

  webapp:
    image: typezero-labs/incontrol-api-core:latest
    build: ./app/
    user: django
    ports:
      - '8000:8000'
    depends_on:
      - database
    env_file:
      - ./environments/local.env
    command: /gunicorn.sh
