FROM python:3.5

ENV PYTHONUNBUFFERED 1

COPY ./requirements /requirements

RUN pip install --upgrade pip \
    && pip install -r /requirements/local.txt \
    && groupadd -r django \
    && useradd -r -g django django

COPY . /app
RUN chown -R django /app

COPY ./scripts/start-dev.sh /start-dev.sh
COPY ./scripts/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh \
    && sed -i 's/\r//' /start-dev.sh \
    && chmod +x /entrypoint.sh \
    && chown django /entrypoint.sh \
    && chmod +x /start-dev.sh \
    && chown django /start-dev.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
